name: wuhoumusic
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dio: ^5.3.2
  audio_service: ^0.18.12
  audio_session: ^0.1.7
  just_audio: ^0.9.34
  permission_handler: ^8.3.0
  rxdart: ^0.27.7
  android_content_provider: ^0.4.0
  path_provider: ^2.0.1
#  device_info_plus: ^9.1.0
  get_it: ^7.6.4
  isar: ^3.1.0+1
  hive_generator: ^2.0.1
  easy_refresh: ^3.3.2+1
  image_picker: ^1.0.3
  fluttertoast: ^8.2.2
  on_audio_query: ^2.9.0
#  uuid: ^3.0.5
  flutter_lyric: ^2.0.4+6
  isar_flutter_libs: ^3.1.0+1
  logger: ^2.0.2+1
#  json_serializable: ^6.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0+1


flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: GuFengLiShu
      fonts:
        - asset: assets/fonts/GuFengLiShu-2.ttf
    - family: LiShuBold
      fonts:
        - asset: assets/fonts/LiShub.ttf
    - family: PuHuiTi
      fonts:
        - asset: assets/fonts/Puhuiti.ttf
    - family: PuHuiTiX
      fonts:
        - asset: assets/fonts/Puhuitix.ttf
    - family: aliIconfont
      fonts:
        - asset: assets/iconfont/ali_iconfont.ttf

